language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - tools/travis_setup.py
install:
    - python setup.py install
    - pip install nose ipython runipy
script:
    - tools/run_tests.sh

